version: '3.8'

services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/acs/nginx:latest
    ports:
      - "5000:80"
    volumes:
      - ./static:/usr/share/nginx/html
    restart: always

  chromadb:
    image: local-chromadb
    ports:
      - "8003:8000"
    volumes:
      - ./chroma_db/data:/chroma/chroma
    restart: always
